# Generated by Django 5.2.1 on 2025-06-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_customer_age_alter_customer_approved_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='monthly_salary',
            new_name='monthly_income',
        ),
    ]
